# Define the config directory
BASH_CONFIG_DIR="$HOME/.config/bash"

for config_file in "$BASH_CONFIG_DIR"/*; do
    # Don't source this file
    if [ "$config_file" != "$BASH_CONFIG_DIR/bashrc" ]; then
        . "$config_file"
    fi
done

# Clean up the variable
unset config_file

